### ISSUE TITLE
Is there a mechanism to kill the camera?

### ISSUE THREAD

**Issue by tylers-username** [franciscop/use-camera#1]
I'm trying to figure out how to kill the video. I thought perhaps passing `false` to `useCamera({'video: false})` but the hook does not detect the change.

Any guidance would be appreciated

**Comment by franciscop** [comment]
You are totally right `video: false` does not work. Since the primary purpose of this library was _to use the camera_, I didn't think people would like to disable the camera (🤷‍♂️) but I can see some value in doing it.

Alternatives:
- PR allowing to disable the video. A case for no video, and a different case for both video and audio disabled.
- A wrapper component that will not render your component+hook if you want the video disabled.
